[server]
headless = true
port     = 8501

[theme]
base                     = "light"
primaryColor             = "#088395"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#EBF4F6"
textColor                = "#071952"
